name: tikino
description: "Todo Application For Android by Ardavan Eskandari"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: ^3.10.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_gen: ^5.9.0
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  persian_datetime_picker: ^3.2.0
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.5+1
  shamsi_date: ^1.1.1
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/tikino.png"

flutter:

  uses-material-design: true

  assets:
    - assets/image/tikino_transparent.png
    - assets/image/tikino.png
    - assets/image/home_appbar_bg.png

  fonts:
    - family: Dana
      fonts:
        - asset: assets/fonts/dana/DanaFaNum-Bold.ttf
          weight: 700

        - asset: assets/fonts/dana/DanaFaNum-Medium.ttf
          weight: 500

        - asset: assets/fonts/dana/DanaFaNum-Regular.ttf
          weight: 400

        - asset: assets/fonts/dana/DanaFaNum-Light.ttf
          weight: 300
