name: purple_do
description: "Todo Application For Android by Ardavan Eskandari"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/iransans/IRANSansXFaNum-Bold.ttf
          weight: 700

        - asset: assets/fonts/iransans/IRANSansXFaNum-Medium.ttf
          weight: 500

        - asset: assets/fonts/iransans/IRANSansXFaNum-Regular.ttf
          weight: 400

        - asset: assets/fonts/iransans/IRANSansXFaNum-Light.ttf
          weight: 300
